# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Dev'
    sourceFolder: '$(build.sourcesDirectory)'
    contents: '**'
    targetFolder: '/build'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'Dev'
    runOptions: 'inline'
    inline: |
      #Unit Testing
      echo "unit testing started"
      if grep 'Fatel' /build/index.html; then
       echo "Test is failed in following number of line"
       sed -n '/Fatel/=' /build/index.html
       exit 1
      fi
      echo "Unit Test is Successful"
    readyTimeout: '20000'